name: Preprocess Dataset CI

on:
  push:
    paths:
      - "Pima Indians Diabetes Database.csv"
      - "preprocessing/**"
      - ".github/workflows/preprocess_ci.yml"

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn seaborn matplotlib joblib

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_FuadHasanWirayudha.py

      - name: Upload processed dataset as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cleaned_dataset
          path: cleaned_pima_diabetes_fuad.csv

